rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text
issue_title,337,idan,oauthlib,lribinik,2015-04-20 12:46:14,"fixing self.redirect_uri to self.redirect_url since self.redirect_uri doesn't exist
",start issue,fix typo in base.py:prepare_authorization_request,fix selfredirecturi selfredirecturl sinc selfredirecturi doesnt exist
issue_closed,337,idan,oauthlib,thedrow,2015-07-01 11:33:29,,closed issue,fix typo in base.py:prepare_authorization_request,
pull_request_title,337,idan,oauthlib,lribinik,2015-04-20 12:46:14,"fixing self.redirect_uri to self.redirect_url since self.redirect_uri doesn't exist
",95f012023a0a6919eeac31903992d8b9df087484,fix typo in base.py:prepare_authorization_request,fix selfredirecturi selfredirecturl sinc selfredirecturi doesnt exist
issue_comment,337,idan,oauthlib,josephtate,2015-05-06 21:14:13,"Seems like we're missing test coverage for this. Any chance you can add one?
",,,seem like miss test coverag ani chanc add one
issue_comment,337,idan,oauthlib,lribinik,2015-05-13 09:59:02,"Will work on adding a test.
",,,will work ad test
issue_comment,337,idan,oauthlib,thedrow,2015-07-01 11:33:29,"Already merged with a test in #351. Thanks.
",,,alreadi merg test 351 thank
issue_comment,337,idan,oauthlib,lribinik,2015-07-01 14:17:14,"Thanks! (Unfortunately wasn't able to get to it)
",,,thank unfortun wasnt abl get
pull_request_commit,337,idan,oauthlib,leon.ribinik@convertro.com,2015-04-20 12:41:17,fixing self.redirect_ui to self.redirect_url since self.redirect_uri doesn't exist,95f012023a0a6919eeac31903992d8b9df087484,,fix selfredirectui selfredirecturl sinc selfredirecturi doesnt exist
