rectype,issueid,project_owner,project_name,actor,time,text,action,title,clean_text,Test
rectype,issueid,project_owner,project_name,actor,time,text,action,title,text,N
issue_title,809,nilearn,nilearn,aabadie,2015-10-30 16:44:29,"As reported in #808, a lot of nilearn tests are failing on windows. There's an issue with the path ot the datasets.

Here is one of the failing ci run : https://ci.appveyor.com/project/aabadie/nilearn/build/job/htt98au0b1j0hxnq
",start issue,Failing tests on windows,As report 808 lot nilearn test fail window there issu path ot dataset here one fail ci run,N
issue_closed,809,nilearn,nilearn,lesteve,2015-11-09 14:36:59,nan,closed issue,Failing tests on windows,nan,N
issue_comment,809,nilearn,nilearn,aabadie,2015-11-02 09:10:37,"> The path problems should be easy to fix

It seems the environ variables are not correctly set on windows. Trying to fix this.
",nan,nan,It seem environ variabl correctli set window tri fix,N
issue_comment,809,nilearn,nilearn,aabadie,2015-11-02 09:17:26,"> It seems the environ variables are not correctly set on windows. Trying to fix this.

Forget about this. The problem is in the logic of _get_dataset_dir
",nan,nan,forget the problem logic getdatasetdir,N
issue_comment,809,nilearn,nilearn,aabadie,2015-11-02 15:04:17,"> You are going to be very limited memory-wise if you want to use nilearn on a 32bit platform

I'm testing locally using a 64 bit version of python and also have the same ""OverflowError: Python int too large to convert to C long"" issue. This problem seems to be related to a call to joblib.Parallel in function ""permuted_ols"" that I don't fully understand.

I could hopefully fix the path related issues.
",nan,nan,Im test local use 64 bit version python also overflowerror python int larg convert C long issu thi problem seem relat call joblibparallel function permutedol I dont fulli understand I could hope fix path relat issu,Y
issue_comment,809,nilearn,nilearn,aabadie,2015-11-02 16:46:10,"I created PR #814 

Remaining issues:
- ""OverflowError: Python int too large to convert to C long"" raised in mass_univariate ""permuted_ol"" function. Some help will be greatly appreciated for this one.
- More problematic is the one concerning the access to multiple opened file at the same time on windows. For example:

``` python
with tempfile.NamedTemporaryFile(suffix='.txt') as fp:
    f = open(fp.name, 'w+b')
    f.write('toto')
    f.close()
```

will fail with the error message: """"""PermissionError: [Errno 13] Permission denied: 'C:\Users\ALEXAN~1\AppData\Local\Temp\tmpuuihk6z6.txt""""""
Same story with:

``` python
with tempfile.NamedTemporaryFile(suffix='.txt') as fp:
    with open(fp.name, 'w+b') as fpp:
        f.write('toto')
```

And this strategy is used intensively in nilearn/plotting/tests/test_img_plotting.py. I could fix the issue here using a temporary string variable and process the filename outside the ""with"" block.
But it's the same kind of context manager behavior used with the function write_tmp_imgs in _utils/testing.py to remove the temporary files on the fly. Here it breaks quite a few tests.
",nan,nan,I creat PR 814 remain issu overflowerror python int larg convert C long rais massunivari permutedol function some help greatli appreci one more problemat one concern access multipl open file time window for exampl fail error messag permissionerror errno 13 permiss deni cusersalexan1appdatalocaltemptmpuuihk6z6txt same stori and strategi use intens nilearnplottingteststestimgplottingpi I could fix issu use temporari string variabl process filenam outsid block but kind context manag behavior use function writetmpimg utilstestingpi remov temporari file fli here break quit test,Y
issue_comment,809,nilearn,nilearn,aabadie,2015-11-03 08:12:33,"@GaelVaroquaux, I agree. But now in the test (see test_img_plotting.py, function test_plot_anat), we use it like what I described above:

``` python
with tempfile.TemporaryFile(suffix='.png') as fp:
    z_slicer.savefig(fp.name) # savefig open another descriptor internally => permission error
```

Using the code below works (of course) but I need a confirmation of the solution:

``` python
filename = """"
with tempfile.TemporaryFile(suffix='.png') as fp:
    filename = fp.name

# tempfile has been removed when exiting the previous context
z_slicer.savefig(filename) # Opens and creates the file again
os.remove(filename)
```
",nan,nan,gaelvaroquaux I agre but test see testimgplottingpi function testplotanat use like I describ use code work cours I need confirm solut,Y
issue_comment,809,nilearn,nilearn,aabadie,2015-11-03 08:15:59,"@GaelVaroquaux, about the overflow error, I made a simple test:

``` python
import numpy as np
a = np.arange(10)
print(a.dtype)
```
- result on windows (using anaconda python 3.4, 64 bits): int32
- result on linux (using same anaconda python 3.4, 64 bits): int64

I think built numpy/scipy provided by anaconda are 32 bits on windows which explains this issue.
",nan,nan,gaelvaroquaux overflow error I made simpl test result window use anaconda python 34 64 bit int32 result linux use anaconda python 34 64 bit int64 I think built numpyscipi provid anaconda 32 bit window explain issu,Y
issue_comment,809,nilearn,nilearn,aabadie,2015-11-03 08:17:41,"> Can you try with a = np.zeros(10) and tell us what you get?

float64...I'm lost
",nan,nan,float64im lost,N
issue_comment,809,nilearn,nilearn,aabadie,2015-11-03 11:00:03,"> OK, so it's indeed a 64bit install, but the default integer is 32bit.
> Interesting.

I created #819 which hopefully (and magically) fixed the issue
",nan,nan,I creat 819 hope magic fix issu,N
issue_comment,809,nilearn,nilearn,aabadie,2015-11-04 07:48:22,"> With the 2 PRs merged, is there still something failing under Windows?

@GaelVaroquaux, yes PR #814 is still pending. There are also
 other problems with context manager in _create_tmp_imgs test utility function that I'd like to fix today.
",nan,nan,gaelvaroquaux ye PR 814 still pend there also problem context manag createtmpimg test util function Id like fix today,Y
issue_comment,809,nilearn,nilearn,aabadie,2015-11-04 15:19:50,"We are getting closer to complete this issue. Just a summary of what is remaining:
- Lots of remaining issues like: 

```
  File ""C:\softs\src\nilearn\nilearn\_utils\testing.py"", line 144, in write_tmp_imgs
    os.remove(filename)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\ALEXAN~1\\AppData\\Local\\Temp\\nilearn_iu926ggu.nii'
```

I tried what @GaelVaroquaux suggested IRL without success. I also tried to remove the contextlib decorator and get the filenames using `list(write_tmp_imgs())` but then it breaks the initial test logic. I need some help on those ones.
- Appveyor raises 3 other issues with python 2.7 but I can't reproduce them locally, see the 3 last ones [here](https://ci.appveyor.com/project/nilearn-ci/nilearn/build/1.0.14/job/nlmqm87exiihnss6)
- I fixed a couple of other ones : one write permission issue was remaining and there was an issue with some the mode parameter of some call to np.memmap.
",nan,nan,We get closer complet issu just summari remain lot remain issu like I tri gaelvaroquaux suggest irl without success I also tri remov contextlib decor get filenam use break initi test logic I need help one appveyor rais 3 issu python 27 I cant reproduc local see 3 last one I fix coupl one one write permiss issu remain issu mode paramet call npmemmap,Y
issue_comment,809,nilearn,nilearn,aabadie,2015-11-05 15:50:55,"@GaelVaroquaux, all tests are passing now on Windows. Just to let you know, we disabled matplotlib as it makes the python interpreter crash at exit with python 3.4. I cannot reproduce this behavior on my system. It's a bit weird.

All the rest is ok.

Maybe we can close this issue (along with #804 until the webhook is added to github).
",nan,nan,gaelvaroquaux test pass window just let know disabl matplotlib make python interpret crash exit python 34 I cannot reproduc behavior system it bit weird all rest ok mayb close issu along 804 webhook ad github,Y
issue_comment,809,nilearn,nilearn,aabadie,2015-11-09 14:26:12,"> For the record, I have added the AppVeyor webhook but it doesn't show in PRs at the moment. I need to investigate more

I confirmed the request sent to nilearn-ci (it uses my personal email). Is it ok now ?
",nan,nan,I confirm request sent nilearnci use person email Is ok,N
issue_comment,809,nilearn,nilearn,GaelVaroquaux,2015-11-03 17:35:08,"With the 2 PRs merged, is there still something failing under Windows?
",nan,nan,with 2 pr merg still someth fail window,N
issue_comment,809,nilearn,nilearn,GaelVaroquaux,2015-11-04 08:05:01,"OK, I just merged #814 
I'll let you tackle the rest and create a PR.
",nan,nan,OK I merg 814 ill let tackl rest creat PR,N
issue_comment,809,nilearn,nilearn,lesteve,2015-11-09 10:14:47,"> Maybe we can close this issue (along with #804 until the webhook is added to github).

For the record, I have added the AppVeyor webhook but it doesn't show in PRs at the moment. I need to investigate more ...
",nan,nan,for record I ad appveyor webhook doesnt show pr moment I need investig,N
issue_comment,809,nilearn,nilearn,lesteve,2015-11-09 14:35:15,"To make a long story short, I had to give nilearn-ci write permission in github, revoke the github link you made in AppVeyor and reauthorize it as nilearn-ci.

One of the resource that was actually helpful:
http://help.appveyor.com/discussions/kb/4-show-multiple-statuses-in-github-pull-requests#comment_36808437

I think this should be OK now, look at https://github.com/nilearn/nilearn/pull/613 (the failure is expected by the way)
",nan,nan,To make long stori short I give nilearnci write permiss github revok github link made appveyor reauthor nilearnci one resourc actual help I think OK look failur expect way,N
issue_comment,809,nilearn,nilearn,lesteve,2015-11-09 14:36:57,"Closing this one I'll open a new issue about the matplotlib segmentation fault on AppVeyor.
",nan,nan,close one ill open new issu matplotlib segment fault appveyor,N
issue_comment,809,nilearn,nilearn,lesteve,2015-11-02 09:00:12,"The path problems should be easy to fix.

The `nilearn.tests.test_signal.test_clean_confounds` one not so sure.
",nan,nan,the path problem easi fix the one sure,N
issue_comment,809,nilearn,nilearn,lesteve,2015-11-02 14:45:50,"Also chatting with @GaelVaroquaux you want to set-up the tests on a 64bit architecture and forget about the 32bit ones. You are going to be very limited memory-wise if you want to use nilearn on a 32bit platform.
",nan,nan,also chat gaelvaroquaux want setup test 64bit architectur forget 32bit one you go limit memorywis want use nilearn 32bit platform,Y
